'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _colorManipulator = require('../utils/colorManipulator');

exports.default = function (theme) {
  return '\n  .mu-raised-button {\n    background-color: ' + theme.background.paper + ';\n    color: ' + theme.text.primary + ';\n  }\n  .mu-raised-button.hover .mu-button-wrapper {\n    background-color: ' + (0, _colorManipulator.fade)(theme.text.primary, 0.1) + ';\n  }\n  .mu-raised-button.mu-inverse.hover  .mu-button-wrapper {\n    background-color: ' + (0, _colorManipulator.fade)(theme.text.alternate, 0.3) + ';\n  }\n  .mu-raised-button.disabled{\n    color: ' + (0, _colorManipulator.fade)(theme.text.primary, 0.3) + ';\n    background-color: ' + (0, _colorManipulator.darken)(theme.text.alternate, 0.1) + ';\n  }\n  .mu-flat-button {\n    color: ' + theme.text.primary + ';\n  }\n  .mu-flat-button.mu-primary-color {\n    color: ' + theme.primary + ';\n  }\n  .mu-flat-button.mu-secondary-color {\n    color: ' + theme.secondary + ';\n  }\n  .mu-flat-button.mu-success-color {\n    color: ' + theme.success + ';\n  }\n  .mu-flat-button.mu-warning-color {\n    color: ' + theme.warning + ';\n  }\n  .mu-flat-button.mu-info-color {\n    color: ' + theme.info + ';\n  }\n  .mu-flat-button.mu-error-color {\n    color: ' + theme.error + ';\n  }\n  .mu-flat-button.hover {\n    background-color: ' + (0, _colorManipulator.fade)(theme.text.primary, 0.1) + ';\n  }\n  .mu-flat-button.disabled {\n    color: ' + theme.text.disabled + ';\n  }\n  .mu-flat-button .mu-circle-ripple {\n    color: ' + theme.text.primary + ';\n  }\n  .mu-icon-button {\n    color: ' + theme.text.primary + ';\n  }\n  .mu-icon-button .mu-circle-ripple{\n    color: ' + theme.text.primary + ';\n  }\n  .mu-icon-button.mu-primary-color {\n    color: ' + theme.primary + ';\n  }\n  .mu-icon-button.mu-secondary-color {\n    color: ' + theme.secondary + ';\n  }\n  .mu-icon-button.mu-success-color {\n    color: ' + theme.success + ';\n  }\n  .mu-icon-button.mu-warning-color {\n    color: ' + theme.warning + ';\n  }\n  .mu-icon-button.mu-info-color {\n    color: ' + theme.info + ';\n  }\n  .mu-icon-button.mu-error-color {\n    color: ' + theme.error + ';\n  }\n  .mu-icon-button.disabled {\n    color: ' + theme.text.disabled + ';\n  }\n  .mu-fab-button {\n    background-color: ' + theme.primary + ';\n    color: ' + theme.text.alternate + ';\n  }\n  .mu-fab-button.hover .mu-button-wrapper,\n  .mu-fab-button:active .mu-button-wrapper {\n    background-color: ' + (0, _colorManipulator.fade)(theme.text.alternate, 0.3) + ';\n  }\n  .mu-fab-button.disabled {\n    color: ' + (0, _colorManipulator.fade)(theme.text.primary, 0.3) + ';\n    background-color: ' + (0, _colorManipulator.darken)(theme.text.alternate, 0.1) + ';\n  }\n  ';
};